# Generated by Django 3.2.8 on 2024-12-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitGym', '0006_alter_ejercicio_descripcion_alter_ejercicio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='imagen',
            field=models.ImageField(default='static/private-files/ImagenDefault.webp', upload_to='', verbose_name='Imagen'),
        ),
    ]
