# Generated by Django 3.2.8 on 2024-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitGym', '0007_alter_entrenamiento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='imagen',
            field=models.ImageField(default='static/private-files/ImagenDefault.webp', upload_to='imagenes_entrenamiento/', verbose_name='Imagen'),
        ),
    ]
